databases:
  - name: VeGaMusic
    ipAllowList: []
    region: Virginia
    plan: free
services:
  - type: web
    plan: free
    name: VeGaMusic
    env: python
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    startCommand: python3 bot.py
    region: Virginia
    envVars:
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: VeGaMusic
          property: connectionString   
    autoDeploy: false
